import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'

export default function ContentDetail({ params }: { params: { id: string } }) {
  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Content: {params.id}</h1>
          <p className="text-[#525252]">Drafting and approval.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline">Reject</Button>
          <Button>Approve & Publish</Button>
        </div>
      </div>
      <Card>
        <CardHeader><CardTitle>Draft Preview</CardTitle></CardHeader>
        <CardContent>
           <div className="prose max-w-none text-sm text-[#525252]">
             <p>This is a simulated piece of content generated by an AI agent.</p>
             <p>It includes formatting, paragraphs, and insights ready for review.</p>
           </div>
        </CardContent>
      </Card>
    </div>
  )
}
