"""Add workspace and brand indexes for pagination

Revision ID: 1456965fba0b
Revises: fdda119ef9f0
Create Date: 2026-10-08 20:38:32.606146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1456965fba0b'
down_revision: Union[str, Sequence[str], None] = 'fdda119ef9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agentrun_brand_id'), 'agentrun', ['brand_id'], unique=False)
    op.create_index(op.f('ix_agentrun_workspace_id'), 'agentrun', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_agenttask_brand_id'), 'agenttask', ['brand_id'], unique=False)
    op.create_index(op.f('ix_agenttask_workspace_id'), 'agenttask', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_approval_workspace_id'), 'approval', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_brand_workspace_id'), 'brand', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_campaign_workspace_id'), 'campaign', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_contentasset_workspace_id'), 'contentasset', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_integration_workspace_id'), 'integration', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspacemember_workspace_id'), 'workspacemember', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspacemember_workspace_id'), table_name='workspacemember')
    op.drop_index(op.f('ix_integration_workspace_id'), table_name='integration')
    op.drop_index(op.f('ix_contentasset_workspace_id'), table_name='contentasset')
    op.drop_index(op.f('ix_campaign_workspace_id'), table_name='campaign')
    op.drop_index(op.f('ix_brand_workspace_id'), table_name='brand')
    op.drop_index(op.f('ix_approval_workspace_id'), table_name='approval')
    op.drop_index(op.f('ix_agenttask_workspace_id'), table_name='agenttask')
    op.drop_index(op.f('ix_agenttask_brand_id'), table_name='agenttask')
    op.drop_index(op.f('ix_agentrun_workspace_id'), table_name='agentrun')
    op.drop_index(op.f('ix_agentrun_brand_id'), table_name='agentrun')
    # ### end Alembic commands ###
