"""Add PerformanceSnapshot model

Revision ID: 2776b8e24c66
Revises: 586f11700647
Create Date: 2026-10-07 19:08:17.972478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2776b8e24c66'
down_revision: Union[str, Sequence[str], None] = '586f11700647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('external_post_id', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('engagements', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('video_views', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_brand_id'), 'performance_snapshots', ['brand_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_captured_at'), 'performance_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_channel'), 'performance_snapshots', ['channel'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_external_post_id'), 'performance_snapshots', ['external_post_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_publication_id'), 'performance_snapshots', ['publication_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_workspace_id'), 'performance_snapshots', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_snapshots_workspace_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_publication_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_external_post_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_channel'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_captured_at'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_brand_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    # ### end Alembic commands ###
