"""Add AgentHandoff model

Revision ID: 37aac9e63ca0
Revises: b066324cbfa6
Create Date: 2026-10-08 22:51:45.025770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37aac9e63ca0'
down_revision: Union[str, Sequence[str], None] = 'b066324cbfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenthandoff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('from_agent', sa.String(), nullable=True),
    sa.Column('to_agent', sa.String(), nullable=True),
    sa.Column('source_run_id', sa.Uuid(), nullable=True),
    sa.Column('input_reference', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['source_run_id'], ['agentrun.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenthandoff_brand_id'), 'agenthandoff', ['brand_id'], unique=False)
    op.create_index(op.f('ix_agenthandoff_from_agent'), 'agenthandoff', ['from_agent'], unique=False)
    op.create_index(op.f('ix_agenthandoff_source_run_id'), 'agenthandoff', ['source_run_id'], unique=False)
    op.create_index(op.f('ix_agenthandoff_to_agent'), 'agenthandoff', ['to_agent'], unique=False)
    op.create_index(op.f('ix_agenthandoff_workspace_id'), 'agenthandoff', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agenthandoff_workspace_id'), table_name='agenthandoff')
    op.drop_index(op.f('ix_agenthandoff_to_agent'), table_name='agenthandoff')
    op.drop_index(op.f('ix_agenthandoff_source_run_id'), table_name='agenthandoff')
    op.drop_index(op.f('ix_agenthandoff_from_agent'), table_name='agenthandoff')
    op.drop_index(op.f('ix_agenthandoff_brand_id'), table_name='agenthandoff')
    op.drop_table('agenthandoff')
    # ### end Alembic commands ###
