"""Add Orchestrator models

Revision ID: 37c2ac3f9cbe
Revises: e3bc34ea3586
Create Date: 2026-10-07 00:46:53.794831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c2ac3f9cbe'
down_revision: Union[str, Sequence[str], None] = 'e3bc34ea3586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestrationrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('output_snapshot', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestrationrun_brand_id'), 'orchestrationrun', ['brand_id'], unique=False)
    op.create_index(op.f('ix_orchestrationrun_workspace_id'), 'orchestrationrun', ['workspace_id'], unique=False)
    op.create_table('orchestratorconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestratorconfig_brand_id'), 'orchestratorconfig', ['brand_id'], unique=True)
    op.create_index(op.f('ix_orchestratorconfig_workspace_id'), 'orchestratorconfig', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orchestratorconfig_workspace_id'), table_name='orchestratorconfig')
    op.drop_index(op.f('ix_orchestratorconfig_brand_id'), table_name='orchestratorconfig')
    op.drop_table('orchestratorconfig')
    op.drop_index(op.f('ix_orchestrationrun_workspace_id'), table_name='orchestrationrun')
    op.drop_index(op.f('ix_orchestrationrun_brand_id'), table_name='orchestrationrun')
    op.drop_table('orchestrationrun')
    # ### end Alembic commands ###
