"""Agent ecosystem updates

Revision ID: 4a2333088fb5
Revises: 37aac9e63ca0
Create Date: 2026-10-09 00:41:43.018000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a2333088fb5'
down_revision: Union[str, Sequence[str], None] = '37aac9e63ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenthandoff', sa.Column('source_agent', sa.String(), nullable=True))
    op.add_column('agenthandoff', sa.Column('destination_agent', sa.String(), nullable=True))
    op.add_column('agenthandoff', sa.Column('destination_run_id', sa.Uuid(), nullable=True))
    op.add_column('agenthandoff', sa.Column('input_context', sa.JSON(), nullable=True))
    op.add_column('agenthandoff', sa.Column('output_reference', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_agenthandoff_from_agent'), table_name='agenthandoff')
    op.drop_index(op.f('ix_agenthandoff_to_agent'), table_name='agenthandoff')
    op.create_index(op.f('ix_agenthandoff_destination_agent'), 'agenthandoff', ['destination_agent'], unique=False)
    op.create_index(op.f('ix_agenthandoff_destination_run_id'), 'agenthandoff', ['destination_run_id'], unique=False)
    op.create_index(op.f('ix_agenthandoff_source_agent'), 'agenthandoff', ['source_agent'], unique=False)
    op.create_foreign_key(None, 'agenthandoff', 'agentrun', ['destination_run_id'], ['id'])
    op.drop_column('agenthandoff', 'from_agent')
    op.drop_column('agenthandoff', 'to_agent')
    op.drop_column('agenthandoff', 'input_reference')
    op.add_column('agentrun', sa.Column('agent_id', sa.String(), nullable=True))
    op.add_column('agentrun', sa.Column('trigger_type', sa.String(), nullable=True))
    op.add_column('agentrun', sa.Column('input_context', sa.JSON(), nullable=True))
    op.add_column('agentrun', sa.Column('output', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('agentrun_task_id_fkey'), 'agentrun', type_='foreignkey')
    op.drop_column('agentrun', 'duration')
    op.drop_column('agentrun', 'retry_count')
    op.drop_column('agentrun', 'task_id')
    op.drop_column('agentrun', 'input_data')
    op.drop_column('agentrun', 'provider')
    op.drop_column('agentrun', 'output_data')
    op.drop_column('agentrun', 'agent_type')
    op.drop_column('agentrun', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentrun', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agentrun', sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agentrun', sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agentrun', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agentrun', sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agentrun', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('agentrun', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agentrun', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agentrun_task_id_fkey'), 'agentrun', 'agenttask', ['task_id'], ['id'])
    op.drop_column('agentrun', 'output')
    op.drop_column('agentrun', 'input_context')
    op.drop_column('agentrun', 'trigger_type')
    op.drop_column('agentrun', 'agent_id')
    op.add_column('agenthandoff', sa.Column('input_reference', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agenthandoff', sa.Column('to_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agenthandoff', sa.Column('from_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'agenthandoff', type_='foreignkey')
    op.drop_index(op.f('ix_agenthandoff_source_agent'), table_name='agenthandoff')
    op.drop_index(op.f('ix_agenthandoff_destination_run_id'), table_name='agenthandoff')
    op.drop_index(op.f('ix_agenthandoff_destination_agent'), table_name='agenthandoff')
    op.create_index(op.f('ix_agenthandoff_to_agent'), 'agenthandoff', ['to_agent'], unique=False)
    op.create_index(op.f('ix_agenthandoff_from_agent'), 'agenthandoff', ['from_agent'], unique=False)
    op.drop_column('agenthandoff', 'output_reference')
    op.drop_column('agenthandoff', 'input_context')
    op.drop_column('agenthandoff', 'destination_run_id')
    op.drop_column('agenthandoff', 'destination_agent')
    op.drop_column('agenthandoff', 'source_agent')
    # ### end Alembic commands ###
