"""add opportunity and dashboard models

Revision ID: 53dbf41766f2
Revises: f1f21a2f0ca8
Create Date: 2026-10-06 22:59:13.489785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dbf41766f2'
down_revision: Union[str, Sequence[str], None] = 'f1f21a2f0ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activityevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activityevent_brand_id'), 'activityevent', ['brand_id'], unique=False)
    op.create_index(op.f('ix_activityevent_workspace_id'), 'activityevent', ['workspace_id'], unique=False)
    op.create_table('metricsnapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricsnapshot_brand_id'), 'metricsnapshot', ['brand_id'], unique=False)
    op.create_index(op.f('ix_metricsnapshot_metric_name'), 'metricsnapshot', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metricsnapshot_workspace_id'), 'metricsnapshot', ['workspace_id'], unique=False)
    op.create_table('opportunity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('effort', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_brand_id'), 'opportunity', ['brand_id'], unique=False)
    op.create_index(op.f('ix_opportunity_workspace_id'), 'opportunity', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_workspace_id'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_brand_id'), table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_index(op.f('ix_metricsnapshot_workspace_id'), table_name='metricsnapshot')
    op.drop_index(op.f('ix_metricsnapshot_metric_name'), table_name='metricsnapshot')
    op.drop_index(op.f('ix_metricsnapshot_brand_id'), table_name='metricsnapshot')
    op.drop_table('metricsnapshot')
    op.drop_index(op.f('ix_activityevent_workspace_id'), table_name='activityevent')
    op.drop_index(op.f('ix_activityevent_brand_id'), table_name='activityevent')
    op.drop_table('activityevent')
    # ### end Alembic commands ###
