"""Add publishing models

Revision ID: 586f11700647
Revises: f03e58675098
Create Date: 2026-10-07 01:50:41.911405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586f11700647'
down_revision: Union[str, Sequence[str], None] = 'f03e58675098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('encrypted_credentials', sa.String(), nullable=True),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('external_account_name', sa.String(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publisher_connections_brand_id'), 'publisher_connections', ['brand_id'], unique=False)
    op.create_index(op.f('ix_publisher_connections_platform'), 'publisher_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_publisher_connections_workspace_id'), 'publisher_connections', ['workspace_id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('content_project_id', sa.UUID(), nullable=False),
    sa.Column('content_draft_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_post_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['content_draft_id'], ['contentdraft.id'], ),
    sa.ForeignKeyConstraint(['content_project_id'], ['contentproject.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_brand_id'), 'publications', ['brand_id'], unique=False)
    op.create_index(op.f('ix_publications_content_draft_id'), 'publications', ['content_draft_id'], unique=False)
    op.create_index(op.f('ix_publications_idempotency_key'), 'publications', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_publications_platform'), 'publications', ['platform'], unique=False)
    op.create_index(op.f('ix_publications_status'), 'publications', ['status'], unique=False)
    op.create_index(op.f('ix_publications_workspace_id'), 'publications', ['workspace_id'], unique=False)
    op.create_table('publication_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_attempts')
    op.drop_index(op.f('ix_publications_workspace_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_status'), table_name='publications')
    op.drop_index(op.f('ix_publications_platform'), table_name='publications')
    op.drop_index(op.f('ix_publications_idempotency_key'), table_name='publications')
    op.drop_index(op.f('ix_publications_content_draft_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_brand_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_publisher_connections_workspace_id'), table_name='publisher_connections')
    op.drop_index(op.f('ix_publisher_connections_platform'), table_name='publisher_connections')
    op.drop_index(op.f('ix_publisher_connections_brand_id'), table_name='publisher_connections')
    op.drop_table('publisher_connections')
    # ### end Alembic commands ###
