"""update agent_id type

Revision ID: 708f04c756af
Revises: 9940843d5430
Create Date: 2026-10-06 23:13:32.105579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708f04c756af'
down_revision: Union[str, Sequence[str], None] = '9940843d5430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aiusageevent_agent_id_fkey', 'aiusageevent', type_='foreignkey')
    op.alter_column('aiusageevent', 'agent_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('aiusageevent_agent_id_fkey'), 'aiusageevent', 'agent', ['agent_id'], ['id'])
    op.alter_column('aiusageevent', 'agent_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
