"""add AIUsageEvent

Revision ID: 9940843d5430
Revises: 53dbf41766f2
Create Date: 2026-10-06 23:08:43.413747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9940843d5430'
down_revision: Union[str, Sequence[str], None] = '53dbf41766f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiusageevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agentrun.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aiusageevent_brand_id'), 'aiusageevent', ['brand_id'], unique=False)
    op.create_index(op.f('ix_aiusageevent_user_id'), 'aiusageevent', ['user_id'], unique=False)
    op.create_index(op.f('ix_aiusageevent_workspace_id'), 'aiusageevent', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aiusageevent_workspace_id'), table_name='aiusageevent')
    op.drop_index(op.f('ix_aiusageevent_user_id'), table_name='aiusageevent')
    op.drop_index(op.f('ix_aiusageevent_brand_id'), table_name='aiusageevent')
    op.drop_table('aiusageevent')
    # ### end Alembic commands ###
