"""Add IntegrationSyncRun model

Revision ID: b066324cbfa6
Revises: eab882659105
Create Date: 2026-10-08 22:49:29.780708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b066324cbfa6'
down_revision: Union[str, Sequence[str], None] = 'eab882659105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrationsyncrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrationsyncrun_brand_id'), 'integrationsyncrun', ['brand_id'], unique=False)
    op.create_index(op.f('ix_integrationsyncrun_integration_id'), 'integrationsyncrun', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integrationsyncrun_provider_id'), 'integrationsyncrun', ['provider_id'], unique=False)
    op.create_index(op.f('ix_integrationsyncrun_workspace_id'), 'integrationsyncrun', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrationsyncrun_workspace_id'), table_name='integrationsyncrun')
    op.drop_index(op.f('ix_integrationsyncrun_provider_id'), table_name='integrationsyncrun')
    op.drop_index(op.f('ix_integrationsyncrun_integration_id'), table_name='integrationsyncrun')
    op.drop_index(op.f('ix_integrationsyncrun_brand_id'), table_name='integrationsyncrun')
    op.drop_table('integrationsyncrun')
    # ### end Alembic commands ###
