"""Add Phase 5 Document fields

Revision ID: da53d3cee5f7
Revises: fa1e78c1ecba
Create Date: 2026-10-08 04:11:00.825919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da53d3cee5f7'
down_revision: Union[str, Sequence[str], None] = 'fa1e78c1ecba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branddocument', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('branddocument', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('branddocument', sa.Column('category', sa.String(), nullable=True))
    op.add_column('branddocument', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('branddocument', sa.Column('retrieval_status', sa.String(), nullable=True))
    op.add_column('branddocument', sa.Column('uploaded_by', sa.Uuid(), nullable=True))
    op.add_column('branddocument', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'branddocument', 'user', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'branddocument', type_='foreignkey')
    op.drop_column('branddocument', 'extracted_text')
    op.drop_column('branddocument', 'uploaded_by')
    op.drop_column('branddocument', 'retrieval_status')
    op.drop_column('branddocument', 'processing_status')
    op.drop_column('branddocument', 'category')
    op.drop_column('branddocument', 'file_size')
    op.drop_column('branddocument', 'file_path')
    # ### end Alembic commands ###
