"""Add Brand Brain Models

Revision ID: e3bc34ea3586
Revises: 708f04c756af
Create Date: 2026-10-06 23:34:40.170102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bc34ea3586'
down_revision: Union[str, Sequence[str], None] = '708f04c756af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('demographics', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('needs', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('buying_triggers', sa.Text(), nullable=True),
    sa.Column('preferred_channels', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_brand_id'), 'audience', ['brand_id'], unique=False)
    op.create_table('branddocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branddocument_brand_id'), 'branddocument', ['brand_id'], unique=False)
    op.create_index(op.f('ix_branddocument_workspace_id'), 'branddocument', ['workspace_id'], unique=False)
    op.create_table('brandstrategy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('business_strategy', sa.Text(), nullable=True),
    sa.Column('marketing_strategy', sa.Text(), nullable=True),
    sa.Column('content_strategy', sa.Text(), nullable=True),
    sa.Column('channel_strategy', sa.Text(), nullable=True),
    sa.Column('growth_strategy', sa.Text(), nullable=True),
    sa.Column('campaign_strategy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brandstrategy_brand_id'), 'brandstrategy', ['brand_id'], unique=True)
    op.create_table('brandvoice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('writing_style', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('formality', sa.String(), nullable=True),
    sa.Column('humor', sa.String(), nullable=True),
    sa.Column('words_to_use', sa.Text(), nullable=True),
    sa.Column('words_to_avoid', sa.Text(), nullable=True),
    sa.Column('messaging_rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brandvoice_brand_id'), 'brandvoice', ['brand_id'], unique=True)
    op.create_table('competitor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_brand_id'), 'competitor', ['brand_id'], unique=False)
    op.create_table('goal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('current_value', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_brand_id'), 'goal', ['brand_id'], unique=False)
    op.create_table('positioning',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('positioning_statement', sa.Text(), nullable=True),
    sa.Column('unique_value_proposition', sa.Text(), nullable=True),
    sa.Column('differentiators', sa.Text(), nullable=True),
    sa.Column('key_messages', sa.Text(), nullable=True),
    sa.Column('proof_points', sa.Text(), nullable=True),
    sa.Column('market_category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positioning_brand_id'), 'positioning', ['brand_id'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_brand_id'), 'product', ['brand_id'], unique=False)
    op.add_column('brand', sa.Column('category', sa.String(), nullable=True))
    op.add_column('brand', sa.Column('location', sa.String(), nullable=True))
    op.add_column('brand', sa.Column('mission', sa.Text(), nullable=True))
    op.add_column('brand', sa.Column('vision', sa.Text(), nullable=True))
    op.add_column('brand', sa.Column('values', sa.Text(), nullable=True))
    op.add_column('brand', sa.Column('tagline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'tagline')
    op.drop_column('brand', 'values')
    op.drop_column('brand', 'vision')
    op.drop_column('brand', 'mission')
    op.drop_column('brand', 'location')
    op.drop_column('brand', 'category')
    op.drop_index(op.f('ix_product_brand_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_positioning_brand_id'), table_name='positioning')
    op.drop_table('positioning')
    op.drop_index(op.f('ix_goal_brand_id'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_competitor_brand_id'), table_name='competitor')
    op.drop_table('competitor')
    op.drop_index(op.f('ix_brandvoice_brand_id'), table_name='brandvoice')
    op.drop_table('brandvoice')
    op.drop_index(op.f('ix_brandstrategy_brand_id'), table_name='brandstrategy')
    op.drop_table('brandstrategy')
    op.drop_index(op.f('ix_branddocument_workspace_id'), table_name='branddocument')
    op.drop_index(op.f('ix_branddocument_brand_id'), table_name='branddocument')
    op.drop_table('branddocument')
    op.drop_index(op.f('ix_audience_brand_id'), table_name='audience')
    op.drop_table('audience')
    # ### end Alembic commands ###
