"""Add StrategyDocument model

Revision ID: eab882659105
Revises: 1456965fba0b
Create Date: 2026-10-08 22:46:59.822311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab882659105'
down_revision: Union[str, Sequence[str], None] = '1456965fba0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategydocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('source_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategydocument_brand_id'), 'strategydocument', ['brand_id'], unique=False)
    op.create_index(op.f('ix_strategydocument_type'), 'strategydocument', ['type'], unique=False)
    op.create_index(op.f('ix_strategydocument_workspace_id'), 'strategydocument', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategydocument_workspace_id'), table_name='strategydocument')
    op.drop_index(op.f('ix_strategydocument_type'), table_name='strategydocument')
    op.drop_index(op.f('ix_strategydocument_brand_id'), table_name='strategydocument')
    op.drop_table('strategydocument')
    # ### end Alembic commands ###
