"""Add content models

Revision ID: f03e58675098
Revises: 37c2ac3f9cbe
Create Date: 2026-10-07 01:19:49.079373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03e58675098'
down_revision: Union[str, Sequence[str], None] = '37c2ac3f9cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentproject',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentproject_brand_id'), 'contentproject', ['brand_id'], unique=False)
    op.create_index(op.f('ix_contentproject_workspace_id'), 'contentproject', ['workspace_id'], unique=False)
    op.create_table('contentbrief',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_project_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('key_message', sa.Text(), nullable=True),
    sa.Column('angle', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('call_to_action', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('competitor_context', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.Column('source_opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['content_project_id'], ['contentproject.id'], ),
    sa.ForeignKeyConstraint(['source_opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentbrief_brand_id'), 'contentbrief', ['brand_id'], unique=False)
    op.create_index(op.f('ix_contentbrief_content_project_id'), 'contentbrief', ['content_project_id'], unique=False)
    op.create_index(op.f('ix_contentbrief_workspace_id'), 'contentbrief', ['workspace_id'], unique=False)
    op.create_table('contentdraft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_project_id', sa.Uuid(), nullable=True),
    sa.Column('brief_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['brief_id'], ['contentbrief.id'], ),
    sa.ForeignKeyConstraint(['content_project_id'], ['contentproject.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentdraft_brand_id'), 'contentdraft', ['brand_id'], unique=False)
    op.create_index(op.f('ix_contentdraft_content_project_id'), 'contentdraft', ['content_project_id'], unique=False)
    op.create_index(op.f('ix_contentdraft_workspace_id'), 'contentdraft', ['workspace_id'], unique=False)
    op.create_table('contentapproval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_project_id', sa.Uuid(), nullable=True),
    sa.Column('content_draft_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['content_draft_id'], ['contentdraft.id'], ),
    sa.ForeignKeyConstraint(['content_project_id'], ['contentproject.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentapproval_brand_id'), 'contentapproval', ['brand_id'], unique=False)
    op.create_index(op.f('ix_contentapproval_workspace_id'), 'contentapproval', ['workspace_id'], unique=False)
    op.create_table('contentversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_draft_id', sa.Uuid(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_draft_id'], ['contentdraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentversion_content_draft_id'), 'contentversion', ['content_draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contentversion_content_draft_id'), table_name='contentversion')
    op.drop_table('contentversion')
    op.drop_index(op.f('ix_contentapproval_workspace_id'), table_name='contentapproval')
    op.drop_index(op.f('ix_contentapproval_brand_id'), table_name='contentapproval')
    op.drop_table('contentapproval')
    op.drop_index(op.f('ix_contentdraft_workspace_id'), table_name='contentdraft')
    op.drop_index(op.f('ix_contentdraft_content_project_id'), table_name='contentdraft')
    op.drop_index(op.f('ix_contentdraft_brand_id'), table_name='contentdraft')
    op.drop_table('contentdraft')
    op.drop_index(op.f('ix_contentbrief_workspace_id'), table_name='contentbrief')
    op.drop_index(op.f('ix_contentbrief_content_project_id'), table_name='contentbrief')
    op.drop_index(op.f('ix_contentbrief_brand_id'), table_name='contentbrief')
    op.drop_table('contentbrief')
    op.drop_index(op.f('ix_contentproject_workspace_id'), table_name='contentproject')
    op.drop_index(op.f('ix_contentproject_brand_id'), table_name='contentproject')
    op.drop_table('contentproject')
    # ### end Alembic commands ###
