"""add user name and constraints

Revision ID: f1f21a2f0ca8
Revises: 8754a571c6c4
Create Date: 2026-10-06 22:46:44.768484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f21a2f0ca8'
down_revision: Union[str, Sequence[str], None] = '8754a571c6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint('uq_workspace_member', 'workspacemember', ['user_id', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_member', 'workspacemember', type_='unique')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
