"""Add WebsiteAnalysis table

Revision ID: fa1e78c1ecba
Revises: 2776b8e24c66
Create Date: 2026-10-08 03:46:39.063114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1e78c1ecba'
down_revision: Union[str, Sequence[str], None] = '2776b8e24c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websiteanalysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=True),
    sa.Column('analysis_results', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websiteanalysis_brand_id'), 'websiteanalysis', ['brand_id'], unique=False)
    op.create_index(op.f('ix_websiteanalysis_workspace_id'), 'websiteanalysis', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websiteanalysis_workspace_id'), table_name='websiteanalysis')
    op.drop_index(op.f('ix_websiteanalysis_brand_id'), table_name='websiteanalysis')
    op.drop_table('websiteanalysis')
    # ### end Alembic commands ###
